-- Test data for movie application generated by AI

-- Genres: Common movie genres for testing
INSERT INTO genres (name, image)
VALUES
    ('Action', 'action.jpg'),
    ('Drama', 'drama.jpg'),
    ('Comedy', 'comedy.jpg'),
    ('Horror', 'horror.jpg'),
    ('Documentary', 'documentary.jpg'),
    ('Science Fiction', 'scifi.jpg'),
    ('Romance', 'romance.jpg'),
    ('Thriller', 'thriller.jpg');

-- Movies: 15 movies with varied ratings, dates, and test scenarios
INSERT INTO movies (title, creation_date, rating, image)
VALUES
    -- Recent releases with different ratings
    ('Test Movie Alpha', '2024-01-15', 'MASTERPIECE', 'movie1.jpg'),
    ('Test Movie Beta', '2024-01-01', 'GREAT', 'movie2.jpg'),
    ('Test Movie Gamma', '2023-12-15', 'DECENT', 'movie3.jpg'),
    ('Test Movie Delta', '2023-12-01', 'MEDIOCRE', 'movie4.jpg'),
    ('Test Movie Epsilon', '2023-11-15', 'UNWATCHABLE', 'movie5.jpg'),

    -- Older releases for date filtering tests
    ('Test Movie Zeta', '2023-06-01', 'MASTERPIECE', 'movie6.jpg'),
    ('Test Movie Eta', '2023-05-15', 'GREAT', 'movie7.jpg'),
    ('Test Movie Theta', '2023-04-01', 'DECENT', 'movie8.jpg'),
    ('Test Movie Iota', '2023-03-15', 'MEDIOCRE', 'movie9.jpg'),
    ('Test Movie Kappa', '2023-02-01', 'UNWATCHABLE', 'movie10.jpg'),

    -- Special cases for edge testing
    ('Test Movie Lambda', '2022-12-31', 'MASTERPIECE', 'movie11.jpg'),    -- Year boundary
    ('Test Movie Mu', '2022-06-15', 'GREAT', 'movie12.jpg'),             -- Mid-year
    ('Test Movie Nu', '2022-01-01', 'DECENT', 'movie13.jpg'),            -- Year start
    ('Test Movie Xi', '2021-12-31', 'MEDIOCRE', 'movie14.jpg'),          -- Previous year
    ('Test Movie Omicron', '2021-06-15', 'UNWATCHABLE', 'movie15.jpg');  -- Oldest

-- Characters: Various attributes for testing search and filters
INSERT INTO characters (name, age, weight, story, image)
VALUES
    ('Test Character A', 20, 70.5, 'Main protagonist for testing', 'char1.jpg'),
    ('Test Character B', 30, 80.0, 'Supporting character for testing', 'char2.jpg'),
    ('Test Character C', 40, 90.5, 'Antagonist for testing', 'char3.jpg'),
    ('Fake Character D', 50, 65.5, 'Minor character for testing', 'char4.jpg'),
    ('Fake Character E', 60, 75.0, 'Background character for testing', 'char5.jpg');

-- Movies-Genres: Complex genre relationships
INSERT INTO movies_genres (movie_id, genre_id)
VALUES
    -- Multiple genres
    (1, 1), (1, 6),  -- Action & Sci-Fi
    (2, 2), (2, 7),  -- Drama & Romance
    (3, 3), (3, 7),  -- Comedy & Romance
    (4, 4), (4, 8),  -- Horror & Thriller
    (5, 5),          -- Documentary only

    -- Mixed combinations
    (6, 1), (6, 2), (6, 6),  -- Action, Drama & Sci-Fi
    (7, 2), (7, 7),          -- Drama & Romance
    (8, 3), (8, 7),          -- Comedy & Romance
    (9, 4), (9, 8),          -- Horror & Thriller
    (10, 5),                 -- Documentary only

    -- Single genres
    (11, 1),  -- Action only
    (12, 2),  -- Drama only
    (13, 3),  -- Comedy only
    (14, 4),  -- Horror only
    (15, 5);  -- Documentary only

-- Movies-Characters: Various relationship patterns
INSERT INTO movies_characters (movie_id, character_id)
VALUES
    -- Multiple characters per movie
    (1, 1), (1, 2), (1, 3),  -- Three characters
    (2, 2), (2, 3),          -- Two characters
    (3, 3),                  -- One character

    -- Shared characters across movies
    (4, 1), (4, 4),
    (5, 2), (5, 5),
    (6, 3), (6, 4),
    (7, 1), (7, 5),

    -- Single character movies
    (8, 1),
    (9, 2),
    (10, 3),
    (11, 4),
    (12, 5),
    (13, 1),
    (14, 2),
    (15, 3);