-- Dummy data generated by AI --

-- Genres
INSERT INTO genres (name, image)
VALUES ('Action', 'https://dummy-images.com/genres/action.png'),
       ('Adventure', 'https://dummy-images.com/genres/adventure.png'),
       ('Science Fiction', 'https://dummy-images.com/genres/scifi.png'),
       ('Fantasy', 'https://dummy-images.com/genres/fantasy.png'),
       ('Drama', 'https://dummy-images.com/genres/drama.png');

-- Movies
INSERT INTO movies (title, creation_date, rating, image)
VALUES ('The Matrix', '1999-03-31', 'MASTERPIECE', 'https://dummy-images.com/movies/matrix.png'),
       ('Lord of the Rings', '2001-12-19', 'MASTERPIECE', 'https://dummy-images.com/movies/lotr.png'),
       ('Inception', '2010-07-16', 'GREAT', 'https://dummy-images.com/movies/inception.png'),
       ('The Dark Knight', '2008-07-18', 'MASTERPIECE', 'https://dummy-images.com/movies/dark-knight.png'),
       ('Interstellar', '2014-11-07', 'UNWATCHABLE', 'https://dummy-images.com/movies/interstellar.png');

-- Characters
INSERT INTO characters (name, age, weight, story, image)
VALUES ('Neo', 35, 75.5, 'The One who freed humanity from the Matrix', 'https://unsplash.com/es/fotos/pajaro-verde-sobre-chaqueta-marron-YiXsjwJKXmo'),
       ('Morpheus', 45, 82.3, 'Leader of the resistance and mentor to Neo',
        'https://unsplash.com/es/fotos/un-robot-azul-con-un-signo-de-interrogacion-en-el-pecho-L5tfgwefMmQ'),
       ('Frodo Baggins', 33, 45.2, 'Ring-bearer from the Shire', 'https://unsplash.com/es/fotos/hombre-con-camisa-blanca-con-sombrero-marron-otKYK0h-5tE'),
       ('Batman', 35, 95.0, 'Billionaire vigilante protecting Gotham',
        'https://unsplash.com/es/fotos/un-animal-de-peluche-sosteniendo-una-pelota-sobre-un-fondo-azul-RDWTEbrvNac'),
       ('Cooper', 45, 80.0, 'Former NASA pilot turned farmer', 'https://unsplash.com/es/fotos/una-figura-rosa-con-signos-de-interrogacion-saliendo-de-ella-UP9aGPmtD6c');

-- Movies-Genres relationships
INSERT INTO movies_genres (movie_id, genre_id)
VALUES (1, 1), -- Matrix - Action
       (1, 3), -- Matrix - Sci-Fi
       (2, 2), -- LOTR - Adventure
       (2, 4), -- LOTR - Fantasy
       (3, 1), -- Inception - Action
       (3, 3), -- Inception - Sci-Fi
       (4, 1), -- Dark Knight - Action
       (4, 5), -- Dark Knight - Drama
       (5, 3), -- Interstellar - Sci-Fi
       (5, 5);
-- Interstellar - Drama

-- Movies-Characters relationships
INSERT INTO movies_characters (movie_id, character_id)
VALUES (1, 1), -- Matrix - Neo
       (1, 2), -- Matrix - Morpheus
       (2, 3), -- LOTR - Frodo
       (4, 4), -- Dark Knight - Batman
       (5, 5); -- Interstellar - Cooper